git-div: avoid graphing base@{push} if it's the same as base
The same check can be added to base@{upstream}, but then we bail out
with a noisy message, which could be modified to say
    (maybe base, @{u}, and @{push} were all the same commit?)
but "silence is success" is nice. The main reason for this is so that
`git div` before a push shows something like I want from `git range-diff
@{push}...` but afterwards compares to @{upstream} so I can see what I'm
proposing. The old behavior (silence after a push) was less than useful
in the common case, leading me to write `git div @ @{u}` more than I'd
like.

Hopefully now `git div` "does what I mean."

diff --git a/links/bin/git-div b/links/bin/git-div
--- a/links/bin/git-div
+++ b/links/bin/git-div
@@ -21,10 +21,26 @@ verbose=
 base=@
 upstream=
 
+rev_parse() {
+  git rev-parse --verify -q "$@"
+}
+
+# $1: suffix for base@{<suffix>} notation
+# $2: optional '=' to skip this suffix if equal to base
+try_upstream() {
+  if ! possible_upstream="$(rev_parse --symbolic "$base@{$1}")"; then
+    return 1
+  fi
+  if test "${2:-}" = = && test "$(rev_parse "$possible_upstream")" = "$(rev_parse "$base")"; then
+    return 1
+  fi
+  upstream=$possible_upstream
+}
+
 set_upstream() {
-  if ! upstream="$(git rev-parse --verify --symbolic -q "$base@{push}")"; then
-    if ! upstream="$(git rev-parse --verify --symbolic -q "$base@{upstream}")"; then
-      die "could not determine upstream for base $base"
+  if ! try_upstream push =; then
+    if ! try_upstream upstream; then
+      die "could not determine useful upstream for base $base"
     fi
   fi
 }
